spring:
  profiles:
       active: 
         -  default
         -  dev
guru:
  username: ymlusername
  password: ymlpassword
  jdbcurl: ymljdbcurl

---
spring:
  profile: prod
guru:
  username: prodymlusername
  password: prodymlpassword
  jdbcurl: prodymljdbcurl
